fix: check the correct port for the container
eclipse-edc/FederatedCatalog pull request #275
Opened 2024-12-17 07:38 UTC by JinsYin

## What this PR changes/adds

_Briefly describe WHAT your pr changes, which features it adds/modifies._

## Why it does that

_Briefly state why the change was necessary._

## Further notes

_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method
signature changes, package declarations, bugs that were encountered and were fixed inline, etc._

## Linked Issue(s)

Closes # <-- _insert Issue number if one exists_

_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.md)._

2024-12-17 07:44 UTC, ndr-brt commented
@JinsYin please follow the contribution guide and do not propose PR out-of-the-blue: https://eclipse-edc.github.io/documentation/for-contributors/guidelines/pr-checklist/

(small doc fix PRs are accepted tho, as the one you opened on IdentityHub)

2024-12-18 02:24 UTC, JinsYin commented
@ndr-brt I have made the necessary changes.

2024-12-18 08:46 UTC, ndr-brt requested changes
It would be nice since we're working here, to add a pair of tests in the pipeline that ensures that the containers are starting correctly.

2024-12-18 08:46 UTC, ndr-brt commented on launchers/catalog-dcp/Dockerfile
> +HEALTHCHECK --interval=5s --timeout=5s --retries=10 CMD curl --fail http://localhost:$WEB_HTTP_PORT/api/check/health
it could worth also to replace the `/api` with `WEB_HTTP_PATH` in the url

2024-12-18 08:46 UTC, ndr-brt commented on launchers/catalog-mocked/Dockerfile
> +HEALTHCHECK --interval=5s --timeout=5s --retries=10 CMD curl --fail http://localhost:$WEB_HTTP_PORT/api/check/health
ditto

2024-12-18 09:07 UTC, JinsYin commented
@ndr-brt Thank you, I have made a new commit.

2024-12-18 13:03 UTC, ndr-brt requested changes

2024-12-18 13:03 UTC, ndr-brt commented on launchers/catalog-dcp/Dockerfile
> +HEALTHCHECK --interval=5s --timeout=5s --retries=10 CMD curl --fail http://localhost:$WEB_HTTP_PORT/$WEB_HTTP_PATH/check/health
```suggestion
HEALTHCHECK --interval=5s --timeout=5s --retries=10 CMD curl --fail http://localhost:$WEB_HTTP_PORT$WEB_HTTP_PATH/check/health
```

please note that the PATH starts with a slash, so it should not be reported in the url

2024-12-18 13:03 UTC, ndr-brt commented on launchers/catalog-mocked/Dockerfile
> +HEALTHCHECK --interval=5s --timeout=5s --retries=10 CMD curl --fail http://localhost:$WEB_HTTP_PORT/$WEB_HTTP_PATH/check/health
ditto. plus, as I said in my previous comment could you add a test for each of these dockerfile that will assert that the containers will start correctly?

2024-12-20 08:08 UTC, ndr-brt commented
@JinsYin updated a comment of mine because tests already exist, but they should be improved to cover the case when the default http port/path are configured

2024-12-20 09:16 UTC, JinsYin commented
@ndr-brt Thank you for your help. As I am not yet familiar with this code, I will need to spend some time.

2024-12-20 10:05 UTC, ndr-brt commented
> @ndr-brt Thank you for your help. As I am not yet familiar with this code, I will need to spend some time.

NP, it's just a call to the `docker` command, you just need to adapt it as the one you reported in the issue and it should be enough:
https://github.com/eclipse-edc/FederatedCatalog/blob/8f8faf4bcedd681c1add51f98194bed9849c59fd/.github/workflows/verify.yaml#L65-L68

2025-01-31 01:56 UTC, closed without merging